services:
  cheekies:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: release
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: cheekies
    environment:
      - GITHUB_TOKEN
    env_file:
      - .env
    volumes:
     - type: bind
       source: ./cheekies.db
       target: /usr/src/app/cheekies.db
    command: bun start
