version: '3.8'

services:
  melon:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: release
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: melon
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    env_file:
      - .env
    volumes:
     - type: bind
       source: ./melon.db
       target: /usr/src/app/melon.db
    command: bun start
