version: '3.8'

services:
  melon:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    container_name: melon
    env_file:
      - .env
    volumes:
      - ./melon.db:/usr/src/app/melon.db
    command: bun start
