version: '3.8'

services:
  melon:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    container_name: melon
    env_file:
      - .env
    volumes:
     - type: bind
       source: ./melon.db
       target: /usr/src/app/melon.db
    command: bun start
