name: Bump Version

on:
  push:
    branches:
        - main

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          skip-tag:  'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
